module.exports = Object.freeze({
  BRAND: 'bookie',
  NAV_LABEL: 'Account access', REGISTER_EYEBROW: 'A NEW CHAPTER', LOGIN_EYEBROW: 'YOUR READING CORNER',
  BOOK_BACK: 'a second chapter', BOOK_NOTE: 'a new shelf, a new story', FOOTER: 'BOOKIE · BOOKS THAT KEEP THEIR STORY GOING',
  LOGIN_TITLE: 'Welcome back.',
  LOGIN_SUBTITLE: 'Your next story is waiting. Sign in and continue where you left off.',
  REGISTER_TITLE: 'Every story has a beginning.',
  REGISTER_SUBTITLE: 'Join readers who give books a second chapter.',
  FIRST_NAME: 'First name', LAST_NAME: 'Last name', EMAIL: 'Email address', PASSWORD: 'Password', REPEAT_PASSWORD: 'Repeat password',
  CITY: 'City', CITY_PLACEHOLDER: 'Choose your city', ROLE: 'How will you use Bookie?',
  BUYER: 'Buyer', SELLER: 'Seller', BUYER_DESCRIPTION: 'I find and exchange books.', SELLER_DESCRIPTION: 'I list and sell my books.',
  GENRES: 'Favorite genres', LANGUAGES: 'Languages you read', INTEREST_HINT: 'Choose at least one option in each group.',
  PASSWORD_LENGTH: 'At least 8 characters', PASSWORD_UPPERCASE: 'One uppercase letter', PASSWORD_NUMBER: 'One number',
  PASSWORD_MATCH: 'Passwords match', PASSWORD_REPEAT_HINT: 'Enter the same password again.',
  SHOW_PASSWORD: 'Show password', HIDE_PASSWORD: 'Hide password',
  LOGIN_BUTTON: 'Log in', REGISTER_BUTTON: 'Create account', SUBMITTING: 'One moment…',
  NO_ACCOUNT: 'Do not have an account yet?', HAS_ACCOUNT: 'Already have an account?', REGISTER_LINK: 'Join us', LOGIN_LINK: 'Log in',
  BACK_HOME: 'Back to books', ALL_REQUIRED: 'All fields are required.',
  LOGIN_NOTICE: 'Your session lasts 2 hours. Log out when you finish on a shared device.',
  FORM_ERROR_TITLE: 'There is one more thing to fix',
  ASIDE_EYEBROW: 'FOR BOOKS. FOR PEOPLE.', ASIDE_TITLE: 'Good books\ndeserve\na second story.',
  ASIDE_BODY: 'Find your next favorite read. Make room on your shelf. Connect with readers in your city.',
  BOOK_TOP: 'ONE MORE CHAPTER', BOOK_TITLE: 'Read.\nShare.\nRepeat.', BOOK_FOOTER: 'THE BOOKIE COLLECTION',
  ASIDE_FOOTER: 'Fewer forgotten books. More new beginnings.',
  ACCOUNT_TITLE: 'Your corner for a new story.', ACCOUNT_SUBTITLE: 'You are signed in successfully. We are glad you are here.',
  ACCOUNT_EMAIL: 'Your email address', ACCOUNT_CITY: 'Your city', ACCOUNT_ROLE: 'Your role',
  EXPLORE: 'Explore books', LOGOUT: 'Log out', ADMIN: 'Administrator', NO_CITY: 'Not selected',
  ERROR_TITLE: 'Something went wrong', NOT_FOUND_TITLE: 'Page not found',
});
