module.exports = Object.freeze({
  BRAND: 'bookie',
  NAV_LABEL: 'Pristup nalogu', REGISTER_EYEBROW: 'NOVO POGLAVLJE', LOGIN_EYEBROW: 'VAŠ ČITALAČKI KUTAK',
  BOOK_BACK: 'drugo poglavlje', BOOK_NOTE: 'nova polica, nova priča', FOOTER: 'BOOKIE · KNJIGE KOJE NASTAVLJAJU PRIČU',
  LOGIN_TITLE: 'Dobro došli nazad.',
  LOGIN_SUBTITLE: 'Vaša sljedeća priča vas čeka. Prijavite se i nastavite gdje ste stali.',
  REGISTER_TITLE: 'Svaka priča ima početak.',
  REGISTER_SUBTITLE: 'Pridružite se čitaocima koji knjigama daju drugo poglavlje.',
  FIRST_NAME: 'Ime', LAST_NAME: 'Prezime', EMAIL: 'Email adresa', PASSWORD: 'Lozinka', REPEAT_PASSWORD: 'Ponovite lozinku',
  CITY: 'Grad', CITY_PLACEHOLDER: 'Odaberite svoj grad', ROLE: 'Kako želite koristiti Bookie?',
  BUYER: 'Kupac', SELLER: 'Prodavač', BUYER_DESCRIPTION: 'Pronalazim i razmjenjujem knjige.', SELLER_DESCRIPTION: 'Objavljujem i prodajem svoje knjige.',
  GENRES: 'Omiljeni žanrovi', LANGUAGES: 'Jezici koje čitate', INTEREST_HINT: 'Odaberite barem jednu opciju u obje grupe.',
  PASSWORD_LENGTH: 'Najmanje 8 znakova', PASSWORD_UPPERCASE: 'Jedno veliko slovo', PASSWORD_NUMBER: 'Jedan broj',
  PASSWORD_MATCH: 'Lozinke se podudaraju', PASSWORD_REPEAT_HINT: 'Unesite istu lozinku još jednom.',
  SHOW_PASSWORD: 'Prikaži lozinku', HIDE_PASSWORD: 'Sakrij lozinku',
  LOGIN_BUTTON: 'Prijavi se', REGISTER_BUTTON: 'Kreiraj nalog', SUBMITTING: 'Samo trenutak…',
  NO_ACCOUNT: 'Još nemate nalog?', HAS_ACCOUNT: 'Već imate nalog?', REGISTER_LINK: 'Pridružite nam se', LOGIN_LINK: 'Prijavite se',
  BACK_HOME: 'Nazad na knjige', ALL_REQUIRED: 'Sva polja su obavezna.',
  LOGIN_NOTICE: 'Prijava traje 2 sata. Odjavite se kada završite na zajedničkom uređaju.',
  FORM_ERROR_TITLE: 'Još samo mali ispravak',
  ASIDE_EYEBROW: 'ZA KNJIGE. ZA LJUDE.', ASIDE_TITLE: 'Dobre knjige\nzaslužuju\ndrugu priču.',
  ASIDE_BODY: 'Pronađite novo omiljeno štivo. Oslobodite mjesto na polici. Povežite se s čitaocima u svom gradu.',
  BOOK_TOP: 'JEDNO POGLAVLJE VIŠE', BOOK_TITLE: 'Čitaj.\nPodijeli.\nPonovi.', BOOK_FOOTER: 'THE BOOKIE COLLECTION',
  ASIDE_FOOTER: 'Manje zaboravljenih knjiga. Više novih početaka.',
  ACCOUNT_TITLE: 'Vaš kutak za novu priču.', ACCOUNT_SUBTITLE: 'Uspješno ste prijavljeni. Drago nam je što ste ovdje.',
  ACCOUNT_EMAIL: 'Vaša email adresa', ACCOUNT_CITY: 'Vaš grad', ACCOUNT_ROLE: 'Vaša uloga',
  EXPLORE: 'Istražite knjige', LOGOUT: 'Odjavi se', ADMIN: 'Administrator', NO_CITY: 'Nije odabran',
  ERROR_TITLE: 'Nešto nije kako treba', NOT_FOUND_TITLE: 'Stranica nije pronađena',
});
