module.exports = Object.freeze({
  VALIDATION_FAILED: 'Check the marked fields and try again.', REQUIRED_FIELD: 'This field is required.',
  INVALID_NAME: 'Enter a name using letters, spaces, hyphens or apostrophes.', NAME_TOO_LONG: 'Names may contain at most 80 characters.',
  INVALID_EMAIL: 'Enter a valid email address.', EMAIL_TOO_LONG: 'Email addresses may contain at most 254 characters.', EMAIL_IN_USE: 'An account with this email already exists. Log in instead.',
  WEAK_PASSWORD: 'Password must contain at least 8 characters, one uppercase letter and one number.', PASSWORD_TOO_LONG: 'Password may contain at most 72 bytes. Choose a shorter password.', PASSWORD_MISMATCH: 'Passwords do not match.',
  INVALID_ROLE: 'Choose buyer or seller.', INVALID_CITY: 'Choose a valid city.', GENRES_REQUIRED: 'Choose at least one genre.', LANGUAGES_REQUIRED: 'Choose at least one language.', INVALID_INTERESTS: 'That selection is no longer available. Choose from the listed options.',
  INVALID_CREDENTIALS: 'The email address or password is incorrect.', ACCOUNT_INACTIVE: 'Your account is inactive. Contact an administrator.', ACCOUNT_BLOCKED: 'Your account is blocked. Contact an administrator.', ACCOUNT_TEMPORARILY_BLOCKED: 'Your account is temporarily blocked. Try again after the block expires.', ACCOUNT_ARCHIVED: 'Your account is archived. Contact an administrator.',
  AUTH_REQUIRED: 'Log in to continue.', SESSION_EXPIRED: 'Your session has expired. Log in again.', INVALID_TOKEN: 'Your session is not valid. Log in again.', SESSION_REVOKED: 'This session is no longer active. Log in again.', FORBIDDEN: 'You do not have permission to perform this action.', CSRF_INVALID: 'This form has expired or is invalid. Refresh the page and try again.',
  TOO_MANY_ATTEMPTS: 'Too many attempts. Try again in 15 minutes.', BAD_REQUEST: 'The request is invalid. Check your details and try again.', PAYLOAD_TOO_LARGE: 'The submitted data is too large. Shorten it and try again.', NOT_FOUND: 'The requested page was not found.', DATABASE_UNAVAILABLE: 'The service is temporarily unavailable. Try again shortly.', INTERNAL_ERROR: 'Something unexpected happened. Try again.', AUTH_CONFIGURATION: 'JWT_SECRET must be set and contain at least 32 characters.',
  BOOK_TITLE_REQUIRED: 'Book title is required.',
  BOOK_AUTHOR_REQUIRED: 'Author is required.',
  BOOK_PUBLISHER_REQUIRED: 'Publisher is required.',
  BOOK_DESCRIPTION_REQUIRED: 'Description is required.',
  BOOK_YEAR_INVALID: 'Enter a valid publication year.',
  BOOK_PRICE_INVALID: 'Price must be a non-negative amount with at most two decimals.',
  BOOK_PRICE_EXCHANGE: 'A book priced at zero must be available for exchange.',
  BOOK_LOOKUP_INVALID: 'Select a valid active genre, language, condition and pickup city.',
  BOOK_IMAGE_INVALID: 'Enter a valid image URL.',
  BOOK_NOT_ALLOWED: 'Only active sellers can publish books.',
  PROFILE_AVATAR_INVALID: 'Enter a valid image URL.',
  PROFILE_UPDATE_FAILED: 'Your profile could not be updated.',
});
