module.exports = Object.freeze({
  VALIDATION_FAILED: 'Provjerite označena polja i pokušajte ponovo.',
  REQUIRED_FIELD: 'Ovo polje je obavezno.',
  INVALID_NAME: 'Unesite ime koristeći slova, razmake, crticu ili apostrof.',
  NAME_TOO_LONG: 'Ime i prezime mogu imati najviše 80 znakova.',
  INVALID_EMAIL: 'Unesite ispravnu email adresu.',
  EMAIL_TOO_LONG: 'Email adresa može imati najviše 254 znaka.',
  EMAIL_IN_USE: 'Nalog s ovom email adresom već postoji. Prijavite se.',
  WEAK_PASSWORD: 'Lozinka mora imati najmanje 8 znakova, jedno veliko slovo i jedan broj.',
  PASSWORD_TOO_LONG: 'Lozinka može imati najviše 72 bajta. Koristite kraću lozinku.',
  PASSWORD_MISMATCH: 'Lozinke se ne podudaraju.',
  INVALID_ROLE: 'Odaberite kupca ili prodavača.',
  INVALID_CITY: 'Odaberite važeći grad.',
  GENRES_REQUIRED: 'Odaberite barem jedan žanr.',
  LANGUAGES_REQUIRED: 'Odaberite barem jedan jezik.',
  INVALID_INTERESTS: 'Odabir više nije dostupan. Odaberite ponuđene opcije.',
  INVALID_CREDENTIALS: 'Email adresa ili lozinka nisu ispravni.',
  ACCOUNT_INACTIVE: 'Vaš nalog nije aktivan. Obratite se administratoru.',
  ACCOUNT_BLOCKED: 'Vaš nalog je blokiran. Obratite se administratoru.',
  ACCOUNT_TEMPORARILY_BLOCKED: 'Vaš nalog je privremeno blokiran. Pokušajte nakon isteka blokade.',
  ACCOUNT_ARCHIVED: 'Vaš nalog je arhiviran. Obratite se administratoru.',
  AUTH_REQUIRED: 'Prijavite se da biste nastavili.',
  SESSION_EXPIRED: 'Vaša prijava je istekla. Prijavite se ponovo.',
  INVALID_TOKEN: 'Prijava nije važeća. Prijavite se ponovo.',
  SESSION_REVOKED: 'Ova prijava više nije aktivna. Prijavite se ponovo.',
  FORBIDDEN: 'Nemate dozvolu za ovu radnju.',
  CSRF_INVALID: 'Obrazac je istekao ili nije važeći. Osvježite stranicu i pokušajte ponovo.',
  TOO_MANY_ATTEMPTS: 'Previše pokušaja. Pokušajte ponovo za 15 minuta.',
  BAD_REQUEST: 'Zahtjev nije ispravan. Provjerite unesene podatke.',
  PAYLOAD_TOO_LARGE: 'Poslani podaci su preveliki. Skratite unos i pokušajte ponovo.',
  NOT_FOUND: 'Tražena stranica ne postoji.',
  DATABASE_UNAVAILABLE: 'Usluga je trenutno nedostupna. Pokušajte ponovo za nekoliko trenutaka.',
  INTERNAL_ERROR: 'Došlo je do neočekivane greške. Pokušajte ponovo.',
  AUTH_CONFIGURATION: 'JWT_SECRET mora biti postavljen i sadržavati najmanje 32 znaka.',
});
