module.exports = Object.freeze({
  RECORD_IN_USE: 'This record is used by an order or another record and cannot be deleted.',
  MESSAGE_INVALID: 'Enter a message between 1 and 5000 characters.',
  CHAT_FORBIDDEN: 'You cannot access this conversation.',
  VALIDATION_FAILED: 'Check the marked fields and try again.',
  REQUIRED_FIELD: 'This field is required.',
  INVALID_NAME: 'Enter a name using letters, spaces, hyphens or apostrophes.',
  NAME_TOO_LONG: 'Names may contain at most 80 characters.',
  INVALID_EMAIL: 'Enter a valid email address.',
  EMAIL_TOO_LONG: 'Email addresses may contain at most 254 characters.',
  EMAIL_IN_USE: 'An account with this email already exists. Log in instead.',
  WEAK_PASSWORD:
    'Password must contain at least 8 characters, one uppercase letter and one number.',
  PASSWORD_TOO_LONG: 'Password may contain at most 72 bytes. Choose a shorter password.',
  PASSWORD_MISMATCH: 'Passwords do not match.',
  INVALID_ROLE: 'Choose buyer or seller.',
  INVALID_CITY: 'Choose a valid city.',
  GENRES_REQUIRED: 'Choose at least one genre.',
  LANGUAGES_REQUIRED: 'Choose at least one language.',
  INVALID_INTERESTS: 'That selection is no longer available. Choose from the listed options.',
  INVALID_CREDENTIALS: 'The email address or password is incorrect.',
  ACCOUNT_INACTIVE: 'Your account is inactive. Contact an administrator.',
  ACCOUNT_BLOCKED: 'Your account is blocked. Contact an administrator.',
  ACCOUNT_TEMPORARILY_BLOCKED:
    'Your account is temporarily blocked. Try again after the block expires.',
  ACCOUNT_ARCHIVED: 'Your account is archived. Contact an administrator.',
  AUTH_REQUIRED: 'Log in to continue.',
  SESSION_EXPIRED: 'Your session has expired. Log in again.',
  INVALID_TOKEN: 'Your session is not valid. Log in again.',
  SESSION_REVOKED: 'This session is no longer active. Log in again.',
  FORBIDDEN: 'You do not have permission to perform this action.',
  CSRF_INVALID: 'This form has expired or is invalid. Refresh the page and try again.',
  TOO_MANY_ATTEMPTS: 'Too many attempts. Try again in 15 minutes.',
  BAD_REQUEST: 'The request is invalid. Check your details and try again.',
  PAYLOAD_TOO_LARGE: 'The submitted data is too large. Shorten it and try again.',
  NOT_FOUND: 'The requested page was not found.',
  DATABASE_UNAVAILABLE: 'The service is temporarily unavailable. Try again shortly.',
  INTERNAL_ERROR: 'Something unexpected happened. Try again.',
  AUTH_CONFIGURATION: 'JWT_SECRET must be set and contain at least 32 characters.',
  BOOK_TITLE_REQUIRED: 'Book title is required.',
  BOOK_AUTHOR_REQUIRED: 'Author is required.',
  BOOK_PUBLISHER_REQUIRED: 'Publisher is required.',
  BOOK_DESCRIPTION_REQUIRED: 'Description is required.',
  BOOK_YEAR_INVALID: 'Enter a valid publication year.',
  BOOK_PRICE_INVALID: 'Price must be a non-negative amount with at most two decimals.',
  BOOK_PRICE_EXCHANGE: 'A book priced at zero must be available for exchange.',
  BOOK_LOOKUP_INVALID: 'Select a valid active genre, language, condition and pickup city.',
  BOOK_IMAGE_INVALID: 'Upload a JPG, PNG or WebP image up to 5 MB.',
  BOOK_NOT_ALLOWED: 'Only active sellers and buyers can publish books.',
  BOOK_NOT_FOUND: 'Book not found.',
  BOOK_STATUS_INVALID: 'This book cannot be edited or archived in its current status.',
  PROFILE_AVATAR_INVALID: 'Upload a JPG, PNG or WebP image up to 5 MB.',
  PROFILE_UPDATE_FAILED: 'Your profile could not be updated.',
  CART_BOOK_INVALID: 'Choose an available book.',
  CART_EMPTY: 'Your cart is empty.',
  CART_OWNER: 'You cannot buy your own book.',
  ORDER_CREATE_FAILED: 'The order could not be created.',
  ORDER_NOT_FOUND: 'Order not found.',
  ORDER_TRANSITION: 'This order cannot change to that status.',
  ORDER_FORBIDDEN: 'You cannot manage this order.',
  EXCHANGE_BOOK_INVALID: 'Choose valid books marked for exchange.',
  REVIEW_NOT_ALLOWED: 'You can review a book only after completing its order.',
  REVIEW_INVALID: 'Rating must be between 1 and 5.',
  REVIEW_EXISTS: 'You already reviewed this book.',
  EMAIL_VERIFICATION_INVALID: 'That verification code is invalid or expired.',
  EMAIL_NOT_VERIFIED: 'Verify your email address before logging in.',
  PHONE_REQUIRED: 'Phone number is required.',
  PHONE_INVALID: 'Enter a valid phone number.',
  UPLOAD_INVALID: 'Upload a JPG, PNG or WebP image up to 5 MB.',
  DUPLICATE_CATALOG: 'An item with this name or code already exists.',
});
