module.exports = Object.freeze({
  ORDER_SUBJECT: 'New Bookie order',
  ORDER_INTRO: 'A buyer wants to purchase the following book(s) from you:',
  BUYER_LABEL: 'Buyer',
  EMAIL_LABEL: 'Email',
  ORDER_LABEL: 'Order',
  TOTAL_LABEL: 'Total',
  CURRENCY: 'BAM',
  DELIVERY_FAILED: 'Order email delivery failed',
  VERIFICATION_SUBJECT: 'Verify your Bookie email',
  VERIFICATION_INTRO: 'Enter this six-digit code to verify your email address:',
  VERIFICATION_EXPIRES: 'This code expires in 15 minutes.',
  PHONE_LABEL: 'Phone',
  OFFER_ACCEPTED_SUBJECT: 'Your Bookie exchange offer was accepted',
  OFFER_REJECTED_SUBJECT: 'Your Bookie exchange offer was rejected',
  OFFER_ACCEPTED_INTRO: 'Good news! Your exchange offer was accepted.',
  OFFER_REJECTED_INTRO: 'Your exchange offer was rejected by the seller.',
  OFFER_BOOK_LABEL: 'Requested book',
  OFFERED_BOOKS_LABEL: 'Books you offered',
  SELLER_LABEL: 'Seller',
});
